# 1. Tensor examples

In [1]:
import torch
# Scalar
scalar = torch.tensor(5.0)
print(f"Scalar: {scalar}")
print(f"Scalar value: {scalar.item()}")  # Convert to a Python number
print(f"Scalar shape: {scalar.shape}")

Scalar: 5.0
Scalar value: 5.0
Scalar shape: torch.Size([])


In [ ]:
# 1D Tensor (Array)
array = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(f"1D Tensor (Array): {array}")
print(f"Array shape: {array.shape}")
print(f"Array sum: {torch.sum(array)}")

1D Tensor (Array): tensor([1., 2., 3., 4.])
Array shape: torch.Size([4])
Array sum: 10.0


In [ ]:
# 2D Tensor (Matrix)
matrix = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(f"2D Tensor (Matrix): {matrix}")
print(f"Matrix shape: {matrix.shape}")
print(f"Matrix transpose: {matrix.t()}")
print(f"Matrix multiplication: {torch.mm(matrix, matrix)}")

2D Tensor (Matrix): tensor([[1., 2.],
        [3., 4.]])
Matrix shape: torch.Size([2, 2])
Matrix transpose: tensor([[1., 3.],
        [2., 4.]])
Matrix multiplication: tensor([[ 7., 10.],
        [15., 22.]])


In [4]:
# 3D Tensor
tensor_3d = torch.randn(2, 3, 1)  # Random 3x4x5 tensor
print(f"3D Tensor: {tensor_3d}")
print(f"3D Tensor shape: {tensor_3d.shape}")

3D Tensor: tensor([[[ 0.3394],
         [ 1.1467],
         [-0.9086]],

        [[ 1.1842],
         [-0.9695],
         [-0.2327]]])
3D Tensor shape: torch.Size([2, 3, 1])


In [ ]:
# Element-wise addition
array1 = torch.tensor([1.0, 2.0, 3.0, 4.0])
array2 = torch.tensor([0.5, 1.5, 2.5, 3.5])
print(f"Element-wise addition: {array1 + array2}")

# Element-wise multiplication
print(f"Element-wise multiplication: {array1 * array2}")

Element-wise addition: tensor([1.5000, 3.5000, 5.5000, 7.5000])
Element-wise multiplication: tensor([ 0.5000,  3.0000,  7.5000, 14.0000])


In [ ]:
# Sum
print(f"Sum of array1: {torch.sum(array1)}")

# Mean
print(f"Mean of array1: {torch.mean(array1)}")

# Maximum
print(f"Max of array1: {torch.max(array1)}")

Sum of array1: 10.0
Mean of array1: 2.5
Max of array1: 4.0


In [ ]:
# transforming a vector with a matrix
matrix = torch.tensor([[1.0, 2.0, 3.0],
                       [4.0, 5.0, 6.0]])

vector = torch.tensor([1.0, 2.0, 3.0])

# Perform matrix-vector multiplication using torch.matmul
result = torch.matmul(matrix, vector)
print(result)

tensor([14., 32.])


# 2. Data loading examples

In [6]:
import torch
from torch.utils.data import TensorDataset, DataLoader, random_split
import seaborn as sns

In [8]:
iris = sns.load_dataset("iris")
# iris is a pandas dataset
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
# get the numpy of the iris dataset
X = iris.drop(columns = ['species']).values
y = iris['species'].astype('category').cat.codes.values
print(X[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [16]:
# convert numpy to tensor
# here label is long type, 64bit int, bc pytorch has optimized for it, CrossEntropyLoss expects long type
# I can use torch.Tensor(X), but that will require pyptorch to do type inference, which can potentially
# cause performance issues. Better to specify the exact type
X_tensor = torch.FloatTensor(X)
y_tensor = torch.LongTensor(y)
# wrap the X and y tensor to the full data before loading to dataloader
full_dataset = TensorDataset(X_tensor, y_tensor)
# it looks like we can't print out the TensorDataset directly like this
print(full_dataset)

# do train test split
train_size = int(0.8*len(full_dataset))
test_size = len(full_dataset) - train_size
train_dataset, test_dataset = random_split(full_dataset, [train_size, test_size])

# now can add the data to the dataloader
train_loader = DataLoader(train_dataset, batch_size = 16, shuffle = True)
test_loader = DataLoader(test_dataset, batch_size = 16, shuffle = False)
# it looks like we can't print out the dataloader directly like this
print(train_loader)